language: go

go:
  - "1.12.x"

env:
- GO111MODULE=on GOLANGCI_RELEASE="v1.16.0"

before_install:
  - go get github.com/mattn/goveralls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_RELEASE}

script:
  - make test
  - make check
  - goveralls -service=travis-ci
  - make
