name: ci
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.15'
    - run: echo "::add-path::$(go env GOPATH)/bin"
    - run: go get github.com/mattn/goveralls
      env:
        GO111MODULE: off
    - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_RELEASE}
      env:
        GOLANGCI_RELEASE: v1.31.0
    - run: |
        make test
        make check
        make
    - run: goveralls -coverprofile=profile.cov -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
